# app/ui/constants/loader_steps.py

from enum import Enum


class LoaderStep(str, Enum):
    # SETUP
    GENERATING_STRUCTURE = "GENERATING_STRUCTURE"
    GENERATING_QUESTIONS = "GENERATING_QUESTIONS"
    GENERATING_TESTS = "GENERATING_TESTS"
    FINALIZING = "FINALIZING"

    # SUBMIT
    SUBMITTING = "SUBMITTING"
    RUNNING_EXECUTION = "RUNNING_EXECUTION"
    ANALYZING = "ANALYZING"
    GENERATING_FEEDBACK = "GENERATING_FEEDBACK"

    # NAVIGATION
    LOADING_NEXT_QUESTION = "LOADING_NEXT_QUESTION"

    # REPORT
    PREPARING_REPORT = "PREPARING_REPORT"
    ANALYZING_RESULTS = "ANALYZING_RESULTS"
    GENERATING_REPORT = "GENERATING_REPORT"
    FINALIZING_REPORT = "FINALIZING_REPORT"


SUBMIT_FLOW = [
    LoaderStep.SUBMITTING,
    LoaderStep.RUNNING_EXECUTION,
    LoaderStep.ANALYZING,
    LoaderStep.GENERATING_FEEDBACK,
]

REPORT_FLOW = [
    LoaderStep.PREPARING_REPORT,
    LoaderStep.ANALYZING_RESULTS,
    LoaderStep.GENERATING_REPORT,
    LoaderStep.FINALIZING_REPORT,
]

SETUP_FLOW = [
    LoaderStep.GENERATING_STRUCTURE,
    LoaderStep.GENERATING_QUESTIONS,
    LoaderStep.GENERATING_TESTS,
    LoaderStep.FINALIZING,
]
