# app/ui/constants/loader_steps.py

from enum import Enum


class LoaderStep(str, Enum):
    # SETUP
    GENERATING_STRUCTURE = "GENERATING_STRUCTURE"
    GENERATING_QUESTIONS = "GENERATING_QUESTIONS"
    GENERATING_TESTS = "GENERATING_TESTS"
    FINALIZING = "FINALIZING"

    # RUNTIME
    SUBMITTING = "SUBMITTING"
    RUNNING_EXECUTION = "RUNNING_EXECUTION"
    ANALYZING = "ANALYZING"
    GENERATING_FEEDBACK = "GENERATING_FEEDBACK"
