# domain/contracts/generated_question.py

# GeneratedQuestion
#
# Represents a question generated by the LLM.
# This is not yet a runtime Question.
# Used for strict JSON validation of LLM output.

from pydantic import BaseModel, Field


class GeneratedQuestion(BaseModel):
    text: str = Field(..., min_length=10)
    difficulty: int = Field(..., ge=1, le=5)

    model_config = {"frozen": True}
