# domain/contracts/interview/loader_step.py

from enum import Enum


class LoaderStep(str, Enum):
    # SETUP
    GENERATING_STRUCTURE = "GENERATING_STRUCTURE"
    GENERATING_QUESTIONS = "GENERATING_QUESTIONS"
    GENERATING_TESTS = "GENERATING_TESTS"
    FINALIZING = "FINALIZING"

    # SUBMIT
    SUBMITTING = "SUBMITTING"
    RUNNING_EXECUTION = "RUNNING_EXECUTION"
    ANALYZING = "ANALYZING"
    GENERATING_FEEDBACK = "GENERATING_FEEDBACK"

    # NAVIGATION
    LOADING_NEXT_QUESTION = "LOADING_NEXT_QUESTION"

    # REPORT
    PREPARING_REPORT = "PREPARING_REPORT"
    ANALYZING_RESULTS = "ANALYZING_RESULTS"
    GENERATING_REPORT = "GENERATING_REPORT"
    FINALIZING_REPORT = "FINALIZING_REPORT"
